### ISSUE TITLE
改进建议：threads下json文件中普遍采用的图片外链的形式，包括了不少指向s1本站的表情以及头像，可能会在关站后无法访问

### ISSUE THREAD

**Issue by gochri** [wing-kai/s1-hibike-archives#1]
`"pid": "27618751",
        "tid": "1085129",
        "first": "0",
        "author": "shadowing",
        "authorid": "219151",
        "dateline": "2014-12-27 17:52",
        "message": "<img src=\"https://static.saraba1st.com/image/smiley/face/149.gif\" />吹这玩意有时髦值吗",`

**Comment by gochri** [comment]
头像也是

**Comment by wing-kai** [comment]
但是把图片全爬下来也没地方放呀，主要的目的还是以保存文本内容为主。
非文本内容的东西爬下来，仓库容量都不知道够不够用了……
